from enum import Enum


class KeyGeneration(Enum):
    """ Determine how keys work for create operations - are they generated by the storage, or specified externally? """
    GENERATED = 'generated'
    SPECIFIED = 'specified'
    OPTIONAL = 'optional'
